### ISSUE TITLE
Airfield names garbled

### ISSUE THREAD

**Issue by jharting** [skylines-project/skylines#442]
Surprisingly quite a few airfields in the Czech Republic have their names garbled on skylines (e.g. Medlamky instead of Medlanky, Krizantov instead of Krizanov etc.) I found more than 10 typos just within CZ names. I know you import the airfield database from welt2000. I tried contacting them at http://www.segelflug.de/vereine/welt2000/ but they never responded.

It kind of hurts to see the name of your homebase misspelled all the time :-(

My question is if any of these would be possible:

1) Does anyone here know the welt2000 authors and can possibly push my changes through? Even better does anyone here have access and can review and apply my changes? I have a patch ready it just needs to get in.

2) Would it be possible to fork welt2000 database under skylines-project org on github? If think that having the database on github would be beneficial anyway (more contributions, better transparency of changes, etc.) I need to double check but I think it is OK with their T&C.

**Comment by Turbo87** [comment]
> 1) Does anyone here know the welt2000 authors and can possibly push my changes through? Even better does anyone here have access and can review and apply my changes? I have a patch ready it just needs to get in.

I was in contact with them a while back, but never really had the time to work on their project.

> 2) Would it be possible to fork welt2000 database under skylines-project org on github? If think that having the database on github would be beneficial anyway (more contributions, better transparency of changes, etc.) I need to double check but I think it is OK with their T&C.

I think that would probably be a good idea. At some point we should probably move away from their text-based file format though and use something more structural like JSON to represent e.g. airfields with multiple runways.

**Comment by jharting** [comment]
> At some point we should probably move away from their text-based file format though and use something more structural like JSON to represent e.g. airfields with multiple runways.

Sounds good to me.

**Comment by jharting** [comment]
So I propose the following steps initially:
1) I can create a github repo, import the data (only their text format for now), readme, yada yada...
2) I fix the misspelled names there
3) You can review and fork under the skylines-project github org
4) Update the skylines app to fetch waypoints from github.com/skylines-project/welt2000 (or whatever the repo name is) instead of the current URL

Later, like you said, this database can be migrated to have more structure.

How does that sound?

**Comment by Turbo87** [comment]
@jharting sounds awesome, thanks for taking care of this!

**Comment by jharting** [comment]
@Turbo87 np, the repo is here: https://github.com/jharting/welt2000

**Comment by jharting** [comment]
@Turbo87 Do you plan on importing that repo under github.com/skylines-project? The repo ^^^ should be ready. I tested importing the new version of the file locally and it worked fine (I did not test it with mapproxy though).

**Comment by Turbo87** [comment]
@jharting I added you to the skylines-project GitHub org. could you try to move the project there? I'm not sure what permissions you need to be able to do that.

**Comment by jharting** [comment]
@Turbo87 I tried transferring the repo but I got `You don’t have admin rights to skylines-project`. Neither am I able to create a new repository under /skylines-project. Looks like I won't be able to transfer the repo withouth admin rights.

However, if you create an empty repo under /skylines-project I think I'll be able to push the content there with the permissions I currently have.

**Comment by Turbo87** [comment]
ah, right, good point. I've created that repo at https://github.com/skylines-project/welt2000 just now.

**Comment by Turbo87** [comment]
also: thanks for taking care of this!

**Comment by jharting** [comment]
@Turbo87 Thank you. One more glitch though :-D Looks like the new repo is not listed here: https://github.com/orgs/skylines-project/teams/developers/repositories

**Comment by Turbo87** [comment]
damn it... I should just give you owner permissions! 😄

**Comment by jharting** [comment]
@Turbo87 OK, I pushed the repo. You may want to set the repo description of https://github.com/skylines-project/welt2000 (I am not authorized to do that still :-). 

The PR to change the import path is here: https://github.com/skylines-project/skylines/pull/456 Let me know once this hits production (or if you run into any problems with the change).

**Comment by jharting** [comment]
@Turbo87 Just curious - do you have an estimate on when to expect this to be live?

**Comment by Turbo87** [comment]
to be honest I'm still a bit afraid to break anything during the update because I've never handled that part myself before. I'll look into backing up that particular table before doing it to make sure we can revert but I haven't found the time yet :-/

**Comment by Turbo87** [comment]
@jharting I've imported the new file now, but somehow it seems that the changes are not being picked up. e.g. https://skylines.aero/flights/airport/1090 is still showing "Krizantov".

**Comment by jharting** [comment]
@Turbo87 Weird, can you see the name updated in the database?

**Comment by Turbo87** [comment]
@jharting it says "Krizantov" too... 😕 

do you have time to debug this? importing the old file and trying to reimport the new file should hopefully reproduce the issue locally. My guess is that the import script is somehow not picking up the new names.

**Comment by jharting** [comment]
@Turbo87 I wanted to reproduce yesterday but I got stuck with Vagrant (some "cannot create postgis extension" error). I'll try again tonight.

**Comment by Turbo87** [comment]
Change the `Vagrantfile` to install `postgresql-9.4-postgis-2.3` instead of `postgresql-9.4-postgis-2.2`. I have a commit for that locally here, but hadn't pushed it yet. No idea though why the old package isn't working anymore.

**Comment by jharting** [comment]
@Turbo87  So what I did was:

1) Spinned up Vagrant with current master (btw that change you suggested did not work for me - more on that later)
2) Modified `skylines/lib/waypoints/welt2000.py` to fetch the airport database from the old location
3) Run the import
4) Verified that I see the old names in the db
5) Created a user, uploaded a flight
6) Verified that I see the old airport name associated with the flight
7) Reverted the change in `skylines/lib/waypoints/welt2000.py`
8) Run the import again

And it worked. After the last step when I run the server again I can see the flight having the new airport name and so does a db query return:

```
skylines=# select id, name from airports where icao = 'LKKA';
  id  |   name   
------+----------
 3520 | Krizanov
(1 row)
```
As the script run I noticed it explicitly logging the changes, e.g.:
```
CZ  Krizantov  LKKA
  name from Krizantov to Krizanov
CZ  Medlamky  LKCM
  name from Medlamky to Medlanky
CZ  Moravsca Trebova  LKMK
...
```

Did you see that as well? Could you by chance omit **--commit** option in the import command?

**Comment by Turbo87** [comment]
> Could you by chance omit --commit option in the import command?

:facepalm:

let me try that again......

**Comment by Turbo87** [comment]
https://skylines.aero/flights/airport/1090 🎉

**Comment by jharting** [comment]
Awesome!! The only thing left is the map server - I can still see old names there.

**Comment by Turbo87** [comment]
yes, there is some maptile caching going on and I have yet to figure out how to reset that cache.
